###########################################################
# Application Configuration
# URL: see src/test/resources/testdata/config.json
###########################################################

###########################################################
# Browser Configuration
###########################################################

browser=chrome
headless=true

###########################################################
# Timeouts (Seconds)
###########################################################

implicit.wait=0
explicit.wait=30
page.load.timeout=30
script.timeout=15

###########################################################
# Browser Behaviour
###########################################################

maximize.window=true
delete.cookies=true

###########################################################
# Screenshot Configuration
###########################################################

screenshot.on.pass=false
screenshot.on.fail=true

###########################################################
# Reporting
###########################################################

extent.report.path=reports/ExtentReport.html

###########################################################
# Execution
###########################################################

parallel.execution=false
thread.count=1

###########################################################
# Logging
###########################################################

log.level=INFO
